# Generated by Django 5.2.6 on 2025-09-13 03:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('duree', models.IntegerField(help_text='Durée en mois', validators=[django.core.validators.MinValueValidator(1)])),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(choices=[('gratuit', 'Gratuit'), ('premium', 'Premium'), ('professionnel', 'Professionnel')], default='gratuit', max_length=15)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu'), ('annule', 'Annulé'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('en_attente', 'En attente'), ('lu', 'Lu'), ('non_lu', 'Non lu')], default='actif', max_length=20)),
                ('nb_annonces_max', models.PositiveIntegerField(default=5)),
                ('nb_photos_max', models.PositiveIntegerField(default=3)),
                ('support_prioritaire', models.BooleanField(default=False)),
                ('mise_en_avant', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Abonnement',
                'verbose_name_plural': 'Abonnements',
            },
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icone', models.URLField(blank=True, null=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sous_categories', to='api.categorie')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu'), ('annule', 'Annulé'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('en_attente', 'En attente'), ('lu', 'Lu'), ('non_lu', 'Non lu')], default='actif', max_length=20)),
                ('type', models.CharField(choices=[('vente', 'Vente'), ('location', 'Location'), ('service', 'Service'), ('emploi', 'Emploi')], default='vente', max_length=10)),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('prix_negociable', models.BooleanField(default=False)),
                ('vues', models.PositiveIntegerField(default=0)),
                ('est_premium', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, help_text='Tags séparés par des virgules', max_length=500)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces', to='api.categorie')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonces',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('derniere_activite', models.DateTimeField(auto_now=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='api.annonce')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Vidéo'), ('document', 'Document')], default='image', max_length=10)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('taille_fichier', models.PositiveIntegerField(blank=True, help_text='Taille en bytes', null=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='api.annonce')),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, help_text='Format: +221123456789', max_length=15, null=True, unique=True)),
                ('nom_utilisateur', models.CharField(max_length=50, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('utilisateur', 'Utilisateur'), ('annonceur', 'Annonceur')], default='utilisateur', max_length=20)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu'), ('annule', 'Annulé'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('en_attente', 'En attente'), ('lu', 'Lu'), ('non_lu', 'Non lu')], default='actif', max_length=20)),
                ('date_derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('photo_profil', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'indexes': [models.Index(fields=['email'], name='api_utilisa_email_678cbb_idx'), models.Index(fields=['nom_utilisateur'], name='api_utilisa_nom_uti_11bfc8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('type', models.CharField(choices=[('message', 'Nouveau message'), ('favori', 'Annonce ajoutée aux favoris'), ('commentaire', 'Nouveau commentaire'), ('expiration', 'Annonce expire bientôt'), ('systeme', 'Notification système')], max_length=15)),
                ('lue', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('annonce', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.annonce')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.utilisateur')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contenu', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu'), ('annule', 'Annulé'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('en_attente', 'En attente'), ('lu', 'Lu'), ('non_lu', 'Non lu')], default='actif', max_length=20)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.conversation')),
                ('expediteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_envoyes', to='api.utilisateur')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.AddField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(related_name='conversations', to='api.utilisateur'),
        ),
        migrations.AddField(
            model_name='annonce',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='api.utilisateur'),
        ),
        migrations.CreateModel(
            name='UtilisateurAbonnement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_souscription', models.DateTimeField(auto_now_add=True)),
                ('date_expiration', models.DateTimeField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu'), ('annule', 'Annulé'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('en_attente', 'En attente'), ('lu', 'Lu'), ('non_lu', 'Non lu')], default='actif', max_length=20)),
                ('auto_renouvellement', models.BooleanField(default=False)),
                ('abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateur_abonnements', to='api.abonnement')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonnements', to='api.utilisateur')),
            ],
            options={
                'verbose_name': 'Abonnement Utilisateur',
                'verbose_name_plural': 'Abonnements Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('mode', models.CharField(choices=[('carte', 'Carte'), ('paypal', 'PayPal'), ('virement', 'Virement'), ('mobile_money', 'Mobile Money'), ('orange_money', 'Orange Money'), ('wave', 'Wave')], default='carte', max_length=15)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu'), ('annule', 'Annulé'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('en_attente', 'En attente'), ('lu', 'Lu'), ('non_lu', 'Non lu')], default='en_attente', max_length=20)),
                ('reference_transaction', models.CharField(max_length=100, unique=True)),
                ('details_transaction', models.JSONField(blank=True, null=True)),
                ('utilisateur_abonnement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='api.utilisateurabonnement')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('adresse', models.CharField(max_length=255)),
                ('ville', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('pays', models.CharField(default='Sénégal', max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('annonce', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='localisation', to='api.annonce')),
            ],
            options={
                'verbose_name': 'Localisation',
                'verbose_name_plural': 'Localisations',
                'indexes': [models.Index(fields=['ville', 'region'], name='api_localis_ville_f35fd8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Signalement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motif', models.CharField(choices=[('spam', 'Spam'), ('contenu_inapproprie', 'Contenu inapproprié'), ('arnaque', 'Arnaque'), ('fausse_annonce', 'Fausse annonce'), ('autre', 'Autre')], max_length=20)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu'), ('annule', 'Annulé'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('en_attente', 'En attente'), ('lu', 'Lu'), ('non_lu', 'Non lu')], default='en_attente', max_length=20)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='api.annonce')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signalements', to='api.utilisateur')),
            ],
            options={
                'verbose_name': 'Signalement',
                'verbose_name_plural': 'Signalements',
                'unique_together': {('utilisateur', 'annonce')},
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='api.annonce')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to='api.utilisateur')),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'unique_together': {('utilisateur', 'annonce')},
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('contenu', models.TextField()),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu'), ('annule', 'Annulé'), ('reussi', 'Réussi'), ('echoue', 'Échoué'), ('en_attente', 'En attente'), ('lu', 'Lu'), ('non_lu', 'Non lu')], default='actif', max_length=20)),
                ('annonce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='api.annonce')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='api.utilisateur')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'unique_together': {('utilisateur', 'annonce')},
            },
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['statut', 'date_publication'], name='api_annonce_statut_560ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['categorie', 'type'], name='api_annonce_categor_5ee46f_idx'),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['utilisateur'], name='api_annonce_utilisa_8d362c_idx'),
        ),
    ]
